# Generated by Django 5.0.4 on 2024-04-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventos',
        ),
    ]
