# Generated by Django 5.0.4 on 2024-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ev', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
