# Generated by Django 5.0.4 on 2024-04-10 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('idDeporte', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('idCampeonato', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=1)),
                ('fecha_inicio', models.DateField()),
                ('idDeporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Desafios',
            fields=[
                ('idDesafio', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('equipo1', models.CharField(max_length=50)),
                ('equipo2', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('ganador', models.CharField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('idEquipo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_eq', models.CharField(max_length=50)),
                ('num_integrantes', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campeonato')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimiento', models.IntegerField()),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
