# Generated by Django 5.0.4 on 2024-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deporte_alter_eventos_descripcion_campeonato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
